version: '2.1'
services:

  # certs:
  #   image: nginx
  #   restart: always
  #   depends_on:
  #     - apigw
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /etc/letsencrypt:/certs
  #     - ./certs/default.conf:/etc/nginx/conf.d/default.conf

  history:
    image: dojot/history
    restart: always
    depends_on:
      - mongodb
    environment:
      FALCON_SETTINGS_MODULE: 'history.settings.docker'
    logging:
      driver: json-file
      options:
        max-size: 100m

  persister:
    image: dojot/persister
    restart: always
    depends_on:
      - mongodb
      - auth
      - kafka
      - data-broker
    environment:
      FALCON_SETTINGS_MODULE: 'history.settings.docker'
    logging:
      driver: json-file
      options:
        max-size: 100m

  mongodb:
    image: "mongo:3.2"
    restart: always
    user: "mongodb"
    logging:
      driver: json-file
      options:
        max-size: 100m

  mqtt:
    image: ansi/mosquitto
    # If TLS is needed, use the image below
    #image: dojot/mqtt-manager
    restart: always
    volumes:
      - ./mqtt/mosquitto.conf:/usr/local/src/mosquitto-1.4.13/mosquitto.conf:Z
    ports:
      - "1883:1883"   # for clear MQTT
      #- "8883:8883"  # for MQTT over TLS
    logging:
      driver: json-file
      options:
        max-size: 100m

  iotagent:
    image: dojot/iotagent-json
    restart: always
    depends_on:
      - mqtt
      - kafka
      - data-broker
    # volumes:
    #   - ./iotagent/config.json:/opt/iotagent-json/config.json:Z
    environment:
       MQTT_TLS: "false"
    logging:
      driver: json-file
      options:
        max-size: 100m

  gui:
    image: dojot/gui:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  # orion replacement component
  data-broker:
    image: dojot/data-broker
    restart: always
    depends_on:
      - kafka
      - data-broker-redis
    logging:
      driver: json-file
      options:
        max-size: 100m

  data-broker-redis:
    image: redis
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  device-manager:
    image: dojot/device-manager
    restart: always
    depends_on:
      - postgres
      - kafka
      - data-broker
    logging:
      driver: json-file
      options:
        max-size: 100m

  auth-redis:
    image: redis
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  image-manager:
    image: dojot/image-manager:latest
    restart: always
    depends_on:
      - postgres
    logging:
      driver: json-file
      options:
        max-size: 100m
    environment:
      # TODO: The following should be unique for each environment
      S3ACCESSKEY: 9HEODSF6WQN5EZ39DM7Z
      S3SECRETKEY: fT5nAgHR9pkj0yYsBdc4p+PPq6ArjshcPdz0HA6W


  minio:
    image:
    restart: always
    image: "minio/minio"
    logging:
      driver: json-file
      options:
        max-size: 100m
    environment:
      # TODO: The following should be unique for each environment
      MINIO_ACCESS_KEY: 9HEODSF6WQN5EZ39DM7Z
      MINIO_SECRET_KEY: fT5nAgHR9pkj0yYsBdc4p+PPq6ArjshcPdz0HA6W


  auth:
    image: dojot/auth:latest
    restart: always
    depends_on:
      - apigw
      - postgres
      - auth-redis
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AUTH_DB_HOST: "postgres"
      AUTH_DB_USER: "kong"
      AUTH_KONG_URL: "http://apigw:8001"
      AUTH_CACHE_HOST: "auth-redis"
      # This is used to select the type of cache to be used. Allowed values are "redis" or "nocache"
      AUTH_CACHE_NAME: "redis"
    logging:
      driver: json-file
      options:
        max-size: 100m

  postgres:
    image: "postgres:9.4"
    restart: always
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_DB: "kong"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        max-size: 100m

  kong-migration:
    image: dojot/kong:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
    command: kong migrations up
    restart: on-failure

  apigw:
    image: dojot/kong:latest
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      kong-migration:
        condition: service_started
    ports:
      - "8000:8000"
      - "8443:8443"
      # - "127.0.0.1:8001:8001"
      # - "7946:7946"
      # - "7946:7946/udp"  # cluster
    environment:
      # The following environment variables could be set for usage with cassandra
      # KONG_DATABASE: "cassandra"
      # KONG_CASSANDRA_CONTACT_POINTS: "cassandra"
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: "postgres"
    volumes:
      - ./apigw/plugins/pep-kong:/plugins/pep-kong
      - ./apigw/plugins/mutualauthentication:/plugins/mutualauthentication
    logging:
      driver: json-file
      options:
        max-size: 100m

  kong-config:
    image: appropriate/curl
    entrypoint: /opt/kong.config.sh
    restart: on-failure
    depends_on:
      - apigw
    volumes:
      - ./kong.config.sh:/opt/kong.config.sh

  flowbroker:
    image: dojot/flowbroker
    restart: always
    depends_on:
      - rabbitmq
      - kafka

  rabbitmq:
    image: rabbitmq
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  alarm-manager:
    image: dojot/alarm-manager:latest
    restart: always
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGO_HOST=mongodb
      - RABBIT_HOST=rabbitmq
    volumes:
      - ./alarms:/opt/jboss/dojot/alarms/metamodel
    logging:
      driver: json-file
      options:
        max-size: 100m

  zookeeper:
    image: "zookeeper:3.4"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 100m

  kafka:
    image: "ches/kafka:0.10.1.1"
    depends_on:
      - zookeeper
    restart: always
    environment:
      ZOOKEEPER_IP: zookeeper
      KAFKA_NUM_PARTITIONS: 10
    logging:
      driver: json-file
      options:
        max-size: 100m

###
# Currently this is only needed if MQTT over TLS is used.
###
#
#  ejbca:
#    image: "dojot/ejbca"
#    restart: always
#    logging:
#      driver: json-file
#      options:
#        max-size: 100m

###
# If mutual authentication is needed, please uncomment these three components below
###
#
#  ma_redis:
#    image: "redis:3.2.8"
#    volumes:
#      - ./ma/redis.conf:/usr/local/etc/redis/redis.conf
#      - ./ma/sentinel.conf:/usr/local/etc/redis/sentinel.conf
#      - ./ma/redis_init.sh:/usr/local/etc/redis/redis_init.sh
#    command: sh -c "chmod +x /usr/local/etc/redis/redis_init.sh && /usr/local/etc/redis/redis_init.sh"
#    logging:
#      driver: json-file
#      options:
#        max-size: 100m
#
#  kerberos:
#    image: "dojot/kerberos"
#    environment:
#      - CASSANDRA_HOSTNAME=cassandra
#      - CASSANDRA_PORT=9042
#    volumes:
#      - ./ma/node.config:/opt/jboss/wildfly/standalone/configuration/node.config
#      - ./ma/kafka.brokers:/opt/jboss/wildfly/standalone/configuration/kafka.brokers
#      - ./ma/redis.sentinels:/opt/jboss/wildfly/standalone/configuration/redis.sentinels
#    depends_on:
#      - kafka
#      - redis
#      - cassandra
#    logging:
#      driver: json-file
#      options:
#        max-size: 100m
#
#  cassandra:
#    image: "cassandra:3.10"
#    logging:
#      driver: json-file
#      options:
#        max-size: 100m
